### ISSUE TITLE
不能加速了

### ISSUE THREAD

**Issue by SimarSima** [chuguofan/chuguo#12]
加速节点列表里什么也没有

**Comment by chuguofan** [comment]
退出重新登陆试下，这会好像防火墙干扰严重，证书都一直被拦截， 如果仍然不行，晚点再重启浏览器试下

2017-09-21 16:13 GMT+08:00 Simar <notifications@github.com>:

**Comment by SimarSima** [comment]
OK ,好用了。谢谢
