### ISSUE TITLE
刚才访问不了google，重新下载插件安装后可以了

### ISSUE THREAD

**Issue by MingJunDuan** [chuguofan/chuguo#14]
总体来说，chuguo还是可以的，帮我找到了很多国外的学习资料。。期望chuguo继续努力，推出更优质的服务。。顺便说下，github的issue这个点子还是不过的，有什么问题，我们可以及时反馈。

**Comment by chuguofan** [comment]
谢谢支持

2017-10-18 0:50 GMT+08:00 Duan <notifications@github.com>:
