### ISSUE TITLE
今天 成都 电信无法使用

### ISSUE THREAD

**Issue by SandyJun** [chuguofan/chuguo#5]
今天 成都 电信无法使用

**Comment by chuguofan** [comment]
您好，请确认您家里电脑是否有安装360安全卫士，360杀毒软件之类的，还有adsafe,如果有请先退出这个再试下，再下载出锅加速助手执行一次就应该正常了,如果仍然不行，请重装下最新版插件

2016-12-10 23:32 GMT+08:00 wang shao jun <notifications@github.com>:
